### ISSUE TITLE
InsecurePlatformWarning on Python 2.7

### ISSUE THREAD

**Issue by tgross** [dry-dock/u14pytall#13]
The version of Python [included in the 2_7.sh](https://github.com/dry-dock/u14pytall/blob/f98e9ad2d15c0f6e370dfbb20c01352be376fbe1/version/2_7.sh#L7) results in an insecure SSL context and the InsecurePlatformWarning:

> /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
>   InsecurePlatformWarning

Unfortunately this breaks a bunch of the tests I'm working on that use Docker Compose to talk to a remote Docker host (Joyent's Triton).

The version shipping for Python 2.7 in Ubuntu 14.04 is 2.7.6 and it wont be backported. The u16 images aren't complete (https://github.com/dry-dock/u16). We might be able to port our test rig over to Python 3, but I wanted to check to see what the timelines for Ubuntu 16 support might be like or whether you'd be interested in a PR to build Python 2.7.9+ in this image as part of the `version/2_7.sh` script.

**Comment by a-murphy** [comment]
Newer versions of Python 2.7 are now available in the Ubuntu 14.04 Python images (versions listed [here](http://docs.shippable.com/platform/runtime/machine-image/language-versions/#python)) and the Ubuntu 16.04 images have been released.
